### ISSUE TITLE
ERROR [internal] load metadata for docker.io/tiangolo/uvicorn-gunicorn-fastapi:python3.10-slim

### ISSUE THREAD

**Issue by NylonDiamond** [lspahija/ultimate-ai-assistant#1]
Getting this when running `docker build -t ultimate_ai_assistant .`:

`ERROR [internal] load metadata for docker.io/tiangolo/uvicorn-gunicorn-fastapi:python3.10-slim`

**Comment by lspahija** [comment]
This issue appears unrelated to this project, but is rather likely related to your local Docker configuration.

Here are some useful links:

https://stackoverflow.com/a/70881149
https://stackoverflow.com/questions/70288986/why-am-i-getting-this-error-error-internal-load-metadata
https://stackoverflow.com/questions/73812700/docker-error-internal-load-metadata-for-docker-io
https://github.com/docker/buildx/issues/476
