### ISSUE TITLE
Include support for Spanish language

### ISSUE THREAD

**Issue by ngosang** [lspahija/ultimate-ai-assistant#2]
Include support for Spanish and other languages. They are supported by GPT and gTTS.
I just did a quick example for Spanish and it's working well.
https://github.com/ngosang/ultimate-ai-assistant/commit/7a90b2e5dc21053dbc71de4b7788b1972b87600e

**Comment by lspahija** [comment]
added support for many languages:
https://github.com/lspahija/ultimate-ai-assistant/commit/d50204156abe2cae321f027f98fc21e9cafe3465

**Comment by ngosang** [comment]
Thank you!
