### ISSUE TITLE
adjust voice 

### ISSUE THREAD

**Issue by Famku** [lspahija/ultimate-ai-assistant#3]
Hi,

is it possible to adjust the voice?

The german voice is way to slow.

Or maybe switch to another voice?

**Comment by lspahija** [comment]
added support for adjusting output audio playback speed: https://github.com/lspahija/ultimate-ai-assistant/commit/762780dea9c5808721cccf187465e24d0d7a5348

**Comment by Famku** [comment]
great, thank you!
